// This file contains mock event data for the timeline demos.

export const mockEventData = {
  'superbowl-lx-2026': {
    title: 'Super Bowl LX 2026',
    startDate: new Date('2026-02-09T03:45:00.000Z'),
    endDate: new Date('2026-02-09T04:45:00.000Z'),
    status: 'completed' as const,
    description:
      "Super Bowl LX at Levi's Stadium - An unforgettable game with an unexpected fourth quarter interruption",
    items: [
      {
        id: 'UxhcAi5REXw',
        timestamp: new Date('2026-02-09T04:09:00.000Z'),
        source: 'Alex Gonzalez',
        sourceUrl: 'https://www.youtube.com/watch?v=UxhcAi5REXw',
        content: 'Fan footage of the Super Bowl streaker sprinting across midfield before security catches up',
        mediaType: 'video' as const,
        mediaUrl: 'https://www.youtube.com/watch?v=UxhcAi5REXw',
      },
      {
        id: 'sb-streaker-1',
        timestamp: new Date('2026-02-09T04:05:00.000Z'),
        source: '@NFLFanatic',
        sourceUrl: 'https://x.com/NFLFanatic/status/1758234567890',
        content: 'LMAO SOMEONE JUST RAN ONTO THE FIELD IN THE MIDDLE OF THE SUPER BOWL 💀💀💀 Security is STRUGGLING #SuperBowlLX',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: 'sb-streaker-2',
        timestamp: new Date('2026-02-09T04:08:00.000Z'),
        source: '@SportsCenter',
        sourceUrl: 'https://x.com/SportsCenter/status/1758234589123',
        content: 'BREAKING: Play has been stopped at Super Bowl LX after a streaker ran onto the field with 12:54 remaining in the 4th quarter',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: 'sb-photo-1',
        timestamp: new Date('2026-02-09T04:09:30.000Z'),
        source: 'Alex Gonzalez fan cam still',
        sourceUrl: 'https://i.ytimg.com/vi/UxhcAi5REXw/maxresdefault.jpg',
        content: 'Still photo from fan footage showing the streaker crossing the Super Bowl logo at midfield',
        mediaType: 'image' as const,
        mediaUrl: 'https://i.ytimg.com/vi/UxhcAi5REXw/maxresdefault.jpg',
      },
      {
        id: 'sb-streaker-3',
        timestamp: new Date('2026-02-09T04:11:00.000Z'),
        source: '@BleacherReport',
        sourceUrl: 'https://x.com/BleacherReport/status/1758234598765',
        content: 'The streaker at Super Bowl LX just became the most talked about person at Levi\'s Stadium tonight',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: 'sb-bsky-1',
        timestamp: new Date('2026-02-09T04:12:00.000Z'),
        source: '@sportsfan.bsky.social',
        sourceUrl: 'https://bsky.app/profile/sportsfan.bsky.social/post/abc123',
        content: 'That streaker had better moves than half the players on the field tonight ngl',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: 'f73TiTWGVVg',
        timestamp: new Date('2026-02-09T04:12:30.000Z'),
        source: 'Footballholics: Live Reactions',
        sourceUrl: 'https://www.youtube.com/watch?v=f73TiTWGVVg',
        content: 'In-stadium style clip of the streaker interruption and crowd reaction during the fourth quarter',
        mediaType: 'video' as const,
        mediaUrl: 'https://www.youtube.com/watch?v=f73TiTWGVVg',
      },
      {
        id: 'sb-photo-2',
        timestamp: new Date('2026-02-09T04:13:00.000Z'),
        source: 'Footballholics frame capture',
        sourceUrl: 'https://i.ytimg.com/vi/f73TiTWGVVg/hqdefault.jpg',
        content: 'Sideline still image of security closing in on the Super Bowl streaker',
        mediaType: 'image' as const,
        mediaUrl: 'https://i.ytimg.com/vi/f73TiTWGVVg/hqdefault.jpg',
      },
      {
        id: 'sb-streaker-4',
        timestamp: new Date('2026-02-09T04:18:00.000Z'),
        source: '@NFL_Memes',
        sourceUrl: 'https://x.com/NFL_Memes/status/1758234612345',
        content: 'Security guard slipped trying to catch the streaker and fell flat on his face 💀 This Super Bowl has EVERYTHING',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: '5GSqQsySHaI',
        timestamp: new Date('2026-02-09T04:20:00.000Z'),
        source: 'USA TODAY',
        sourceUrl: 'https://www.youtube.com/watch?v=5GSqQsySHaI',
        content: 'Media recap of the Super Bowl streaker incident and what happened right after the tackle',
        mediaType: 'video' as const,
        mediaUrl: 'https://www.youtube.com/watch?v=5GSqQsySHaI',
      },
      {
        id: 'Rj_-X_HrtAU',
        timestamp: new Date('2026-02-09T04:23:00.000Z'),
        source: 'Elite Picks',
        sourceUrl: 'https://www.youtube.com/watch?v=Rj_-X_HrtAU',
        content: 'POV angle from the stands showing the streaker weaving past security at the Super Bowl',
        mediaType: 'video' as const,
        mediaUrl: 'https://www.youtube.com/watch?v=Rj_-X_HrtAU',
      },
      {
        id: 'sb-streaker-5',
        timestamp: new Date('2026-02-09T04:25:00.000Z'),
        source: '@TotalProSports',
        sourceUrl: 'https://x.com/TotalProSports/status/1758234634567',
        content: 'The streaker delay might have actually given the offense time to reset their strategy. 4D chess move? 🤔 #SuperBowlLX',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
      {
        id: 'sb-streaker-6',
        timestamp: new Date('2026-02-09T04:28:00.000Z'),
        source: '@barstoolsports',
        sourceUrl: 'https://x.com/barstoolsports/status/1758234645678',
        content: 'That streaker just paid $5000 for a stadium ban and internet immortality. Worth it tbh',
        mediaType: 'text' as const,
        mediaUrl: undefined,
      },
    ],
    pendingLiveItems: [],
  },
};

export type EventId = keyof typeof mockEventData;
export type EventData = (typeof mockEventData)[EventId];
